name: Run Robot Framework UI Tests and Update Results to MySQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  process-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install flask mysql-connector-python xml.etree.ElementTree

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Run XML Processing Script
        run: python xml_to_db.py

  test-ui:
    runs-on: ubuntu-latest
    needs: process-xml  # ต้องรอให้ XML Processing เสร็จก่อนถึงจะรัน UI Tests ได้

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary webdriver-manager

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      - name: Start Xvfb (Virtual Display)
        run: Xvfb :99 -screen 0 1920x1080x24 -ac &
        env:
          DISPLAY: :99

      - name: Ensure Results Directory Exists
        run: mkdir -p results/

      - name: Run Robot Framework UI Tests
        run: DISPLAY=:99 robot --outputdir results/ tests/
        continue-on-error: true

      - name: List results directory
        run: ls -lah results/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/

      - name: Update Test Results to Database
        run: python xml_to_db.py results/output.xml
