name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager  # ✅ ติดตั้ง WebDriver Manager

      - name: Install Chrome and WebDriver using WebDriver Manager
        run: |
          python -m pip install webdriver-manager
          CHROMEDRIVER_PATH=$(python -c "from webdriver_manager.chrome import ChromeDriverManager; print(ChromeDriverManager().install())")
          echo "CHROMEDRIVER_PATH=${CHROMEDRIVER_PATH}"
          echo "export PATH=$CHROMEDRIVER_PATH:$PATH" >> $GITHUB_ENV


      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
