name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chrome Driver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%.*})
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          rm /tmp/chromedriver.zip

      - name: Set Chrome Options
        run: |
          mkdir -p /tmp/chrome-user-data
          echo "ROBOT_OPTIONS=--variable OPTIONS:--user-data-dir=/tmp/chrome-user-data,--no-sandbox,--disable-dev-shm-usage" >> $GITHUB_ENV

      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
