name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install webdriver-manager
          pip install chromedriver-autoinstaller

      - name: Install Google Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -c "import chromedriver_autoinstaller; chromedriver_autoinstaller.install()"
          echo "Chrome and ChromeDriver installed successfully"

      - name: Set Chrome Options
        run: |
          echo "ROBOT_OPTIONS=--variable BROWSER:chrome --variable OPTIONS:--headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--remote-debugging-port=9222" >> $GITHUB_ENV
          echo "Chrome options set successfully"

      - name: Debug Chrome Installation
        run: |
          google-chrome --version
          chromedriver --version
          which google-chrome
          which chromedriver

      - name: Run Robot Framework Tests
        run: |
          robot --outputdir results tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
