name: Run Robot Framework Tests with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Check Chrome & ChromeDriver Version
        run: |
          google-chrome --version
          chromedriver --version

      - name: Run Robot Framework Tests in Headless Mode
        run: |
          robot --loglevel TRACE -d results tests/
        env:
          BROWSER: chrome
          SELENIUM_OPTIONS: --headless=new --disable-gpu --no-sandbox --disable-dev-shm-usage

      - name: Compress test results
        run: |
          zip -r report.zip results/

      - name: Upload report.zip
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.zip
