name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: |
          pip install playwright
          playwright install chromium
          echo "CHROME_BIN=$(playwright print-chromium-executable)" >> $GITHUB_ENV

      - name: Install ChromeDriver for Playwright Chromium
        run: |
          CHROME_VERSION=$(playwright print-chromium-executable --version | awk '{print $2}' | cut -d '.' -f1)
          DRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0.0/chromedriver_linux64.zip"
          wget -q -O chromedriver.zip $DRIVER_URL
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver.zip


      - name: Run Robot Framework Tests
        run: robot --outputdir results/ tests/
        continue-on-error: true

      - name: List results directory
        run: ls -lah results/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
