name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get install -f -y
          rm google-chrome.deb
          echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
          DRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip"

          echo "Downloading ChromeDriver for Chrome version: $CHROME_VERSION"
          wget -q -O chromedriver.zip $DRIVER_URL || { echo "❌ ChromeDriver not found for version $CHROME_VERSION"; exit 1; }

          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver.zip

          chromedriver --version


      - name: Run Robot Framework Tests
        run: robot --outputdir results/ tests/
        continue-on-error: true

      - name: List results directory
        run: ls -lah results/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
