name: Run Robot Framework UI Tests and Update Results to MySQL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install flask mysql-connector-python robotframework robotframework-seleniumlibrary webdriver-manager
          echo "Python path: $(which python)"
          echo "Robot path: $(which robot)"

      - name: Cache Python Packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

  test-ui:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      - name: Start Xvfb (Virtual Display)
        run: Xvfb :99 -screen 0 1920x1080x24 -ac &
        env:
          DISPLAY: :99

      - name: Ensure Results Directory Exists
        run: mkdir -p results/

      - name: Run Robot Framework UI Tests
        run: DISPLAY=:99 python -m robot --outputdir results/ tests/
        continue-on-error: true

      - name: List results directory
        run: ls -lah results/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/

  process-xml:
    runs-on: ubuntu-latest
    needs: test-ui

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Download UI Test Results
        uses: actions/download-artifact@v4
        with:
          name: robot-test-results
          path: results/

      - name: Update Test Results to Database
        run: python xml_to_db.py results/output.xml
