name: Run Robot Framework Tests with Selenium

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Chrome & WebDriver
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Run Robot Framework Tests
        run: |
          robot -d results tests/

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
