name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies (No venv)
        run: |
          pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary webdriver-manager

      - name: Install or Update Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable
          google-chrome --version

      - name: Kill Chrome Instances (Prevent Session Issues)
        run: |
          pkill chrome || true

      - name: Ensure Results Directory Exists
        run: mkdir -p results/

      - name: Run Robot Framework Tests
        run: robot --outputdir results/ tests/
        continue-on-error: true

      - name: List results directory
        run: ls -lah results/

      - name: Compress Test Results to ZIP
        run: |
          echo "Compressing test results..."
          cd results || exit 1
          zip -r robot-test-results.zip * || echo "❌ Failed to create ZIP!"

      - name: Verify ZIP File Exists
        run: |
          echo "Checking if ZIP file exists..."
          ls -la results/robot-test-results.zip || echo "❌ ZIP file not found!"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/robot-test-results.zip
