name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Google Chrome & ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip

          # Download Google Chrome
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

          # Install Google Chrome with error handling
          sudo dpkg -i google-chrome.deb || true  # Ignore errors from dpkg
          sudo apt-get install -f -y  # Fix missing dependencies
          rm google-chrome.deb

          # Verify installation
          google-chrome --version || echo "Google Chrome installation failed, but continuing."

          # Install matching ChromeDriver
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          DRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROME_VERSION}.0.0/chromedriver_linux64.zip"

          wget -q -O chromedriver.zip $DRIVER_URL
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          rm chromedriver.zip

          # Set environment variables
          echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
          echo "CHROMEDRIVER=$(which chromedriver)" >> $GITHUB_ENV



      - name: Run Robot Framework Tests
        run: robot --outputdir results/ tests/
        continue-on-error: true

      - name: List results directory
        run: ls -lah results/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
